// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Location recommendation AI agent.
 *
 * - generateLocationRecommendations - A function that handles the location recommendation process.
 * - GenerateLocationRecommendationsInput - The input type for the generateLocationRecommendations function.
 * - GenerateLocationRecommendationsOutput - The return type for the generateLocationRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateLocationRecommendationsInputSchema = z.object({
  categories: z
    .string()
    .describe('The categories of places to recommend, separated by commas.'),
  details: z.string().describe('Details about your friend\'s preferences.'),
  address: z.string().describe('The address of your friend\'s new place of stay.'),
});
export type GenerateLocationRecommendationsInput = z.infer<
  typeof GenerateLocationRecommendationsInputSchema
>;

const GenerateLocationRecommendationsOutputSchema = z.object({
  recommendations: z
    .string()
    .describe('A list of recommended places near your friend\'s new place of stay.'),
});
export type GenerateLocationRecommendationsOutput = z.infer<
  typeof GenerateLocationRecommendationsOutputSchema
>;

export async function generateLocationRecommendations(
  input: GenerateLocationRecommendationsInput
): Promise<GenerateLocationRecommendationsOutput> {
  return generateLocationRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateLocationRecommendationsPrompt',
  input: {schema: GenerateLocationRecommendationsInputSchema},
  output: {schema: GenerateLocationRecommendationsOutputSchema},
  prompt: `You are a recommendation engine that suggests locations based on the provided information.\n\nCategories: {{{categories}}}\nDetails: {{{details}}}\nAddress: {{{address}}}\n\nGenerate a list of recommended places near the provided address, ensuring the recommendations match the provided categories and details about your friend's preferences.\n\nMake sure to include businesses that would appeal to your friend.`,
});

const generateLocationRecommendationsFlow = ai.defineFlow(
  {
    name: 'generateLocationRecommendationsFlow',
    inputSchema: GenerateLocationRecommendationsInputSchema,
    outputSchema: GenerateLocationRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
